### ISSUE TITLE
ServiceState not available after waitForData

### ISSUE THREAD

**Issue by THuppke** [openbase/bco.dal#1]
When calling waitForData() and afterwards getPowerState() on a PowerStateServiceRemote the following error may occur:

```
Caused by: org.openbase.jul.exception.NotAvailableException: Context[servicestate] is not available!
    at org.openbase.bco.dal.remote.service.AbstractServiceRemote.getServiceState(AbstractServiceRemote.java:114)
    at org.openbase.bco.dal.remote.service.PowerStateServiceRemote.getPowerState(PowerStateServiceRemote.java:73)
    at de.citec.csra.RegistryObjectManager.processSelectedObject(RegistryObjectManager.java:181)
```

**Comment by DivineThreepwood** [comment]
This issue is already solved, right?

@THuppke: Can you confirm this?
