### ISSUE TITLE
Shutdown problems related to configuration changes while running. Also see (Issues #114 and #115)

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.dal#116]
In issues #114 and #115 I posted problems that happened when I changed labels and locations of units during runtime. I think this also correlates with the following errors that happened when I shutdown this BCO instance: 

<pre>
09:56:33.172 [pool-1-thread-71] WARN  o.o.b.d.r.u.ColorableLightRemote Something went wrong during data request, maybe the connection or activation state has just changed so all checks will be performed again...
org.openbase.jul.exception.InvalidStateException: Could not call Method[requestStatus] asynchronous because of a middleware issue!
	at org.openbase.jul.extension.rsb.com.RSBSynchronizedRemoteServer.callAsync(RSBSynchronizedRemoteServer.java:138)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.internalRequestStatus(RSBRemoteService.java:1140)
	at org.openbase.bco.authentication.lib.com.AbstractAuthenticatedConfigurableRemote.internalRequestStatus(AbstractAuthenticatedConfigurableRemote.java:62)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService$SyncTaskCallable.call(RSBRemoteService.java:1067)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService$SyncTaskCallable.call(RSBRemoteService.java:1010)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: null
	at rsb.transport.spread.SpreadReceiver$State.activate(SpreadReceiver.java:197)
	at rsb.transport.spread.SpreadReceiver.activate(SpreadReceiver.java:344)
	at rsb.transport.spread.SpreadMultiReceiver.subscribe(SpreadMultiReceiver.java:246)
	at rsb.transport.spread.MultiSpreadInPushConnector.activate(MultiSpreadInPushConnector.java:114)
	at rsb.eventprocessing.RouteConfiguratorUtility.activate(RouteConfiguratorUtility.java:90)
	at rsb.eventprocessing.DefaultPushInRouteConfigurator.activate(DefaultPushInRouteConfigurator.java:69)
	at rsb.Listener$StateInactive.activate(Listener.java:122)
	at rsb.Listener.activate(Listener.java:190)
	at rsb.patterns.Method$StateInactive.activate(Method.java:108)
	at rsb.patterns.Method.activate(Method.java:201)
	at rsb.patterns.RemoteServer.addMethod(RemoteServer.java:452)
	at rsb.patterns.RemoteServer.callAsyncEvent(RemoteServer.java:394)
	at rsb.patterns.RemoteServer.callAsync(RemoteServer.java:116)
	at rsb.patterns.RemoteServer.callAsync(RemoteServer.java:137)
	at org.openbase.jul.extension.rsb.com.RSBSynchronizedRemoteServer.callAsync(RSBSynchronizedRemoteServer.java:130)
	... 8 common frames omitted
09:56:33.177 [pool-2-thread-10] WARN  o.o.j.s.WatchDog ═╦═⚀ Could not start Service[RSBListener[/home/wohnzimmer/dimmablelight/leselampe/status/]] try again in 10 seconds...
09:56:33.177 [pool-2-thread-10] WARN  o.o.j.s.WatchDog  ╚══╦═⚀ Could not activate listener!
09:56:33.177 [pool-2-thread-10] WARN  o.o.j.s.WatchDog     ╚════⚀ IllegalStateException
09:56:33.178 [pool-2-thread-10] WARN  o.o.j.s.WatchDog =====================================
09:56:33.172 [pool-1-thread-98] WARN  o.o.b.d.r.u.ColorableLightRemote Something went wrong during data request, maybe the connection or activation state has just changed so all checks will be performed again...
org.openbase.jul.exception.InvalidStateException: Could not call Method[requestStatus] asynchronous because of a middleware issue!
	at org.openbase.jul.extension.rsb.com.RSBSynchronizedRemoteServer.callAsync(RSBSynchronizedRemoteServer.java:138)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.internalRequestStatus(RSBRemoteService.java:1140)
	at org.openbase.bco.authentication.lib.com.AbstractAuthenticatedConfigurableRemote.internalRequestStatus(AbstractAuthenticatedConfigurableRemote.java:62)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService$SyncTaskCallable.call(RSBRemoteService.java:1067)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService$SyncTaskCallable.call(RSBRemoteService.java:1010)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: null
	at rsb.transport.spread.SpreadReceiver$State.activate(SpreadReceiver.java:197)
	at rsb.transport.spread.SpreadReceiver.activate(SpreadReceiver.java:344)
	at rsb.transport.spread.SpreadMultiReceiver.subscribe(SpreadMultiReceiver.java:246)
	at rsb.transport.spread.MultiSpreadInPushConnector.activate(MultiSpreadInPushConnector.java:114)
	at rsb.eventprocessing.RouteConfiguratorUtility.activate(RouteConfiguratorUtility.java:90)
	at rsb.eventprocessing.DefaultPushInRouteConfigurator.activate(DefaultPushInRouteConfigurator.java:69)
	at rsb.Listener$StateInactive.activate(Listener.java:122)
	at rsb.Listener.activate(Listener.java:190)
	at rsb.patterns.Method$StateInactive.activate(Method.java:108)
	at rsb.patterns.Method.activate(Method.java:201)
	at rsb.patterns.RemoteServer.addMethod(RemoteServer.java:452)
	at rsb.patterns.RemoteServer.callAsyncEvent(RemoteServer.java:394)
	at rsb.patterns.RemoteServer.callAsync(RemoteServer.java:116)
	at rsb.patterns.RemoteServer.callAsync(RemoteServer.java:137)
	at org.openbase.jul.extension.rsb.com.RSBSynchronizedRemoteServer.callAsync(RSBSynchronizedRemoteServer.java:130)
	... 8 common frames omitted
09:56:33.173 [pool-2-thread-4] ERROR o.o.j.s.RecurrenceEventFilter ═══⚀ Shutdown in progress
09:56:33.180 [pool-2-thread-4] ERROR o.o.j.s.RecurrenceEventFilter =====================================
09:56:33.180 [pool-2-thread-4] ERROR o.o.j.s.RecurrenceEventFilter Shutdown in progress
java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
	at org.openbase.jul.iface.Shutdownable$ShutdownDaemon.<init>(Shutdownable.java:92)
	at org.openbase.jul.iface.Shutdownable$ShutdownDaemon.<init>(Shutdownable.java:74)
	at org.openbase.jul.iface.Shutdownable.registerShutdownHook(Shutdownable.java:55)
	at org.openbase.jul.extension.rsb.com.RSBCommunicationService.<init>(RSBCommunicationService.java:140)
	at org.openbase.jul.extension.rsb.com.AbstractIdentifiableController.<init>(AbstractIdentifiableController.java:40)
	at org.openbase.jul.extension.rsb.com.AbstractConfigurableController.<init>(AbstractConfigurableController.java:53)
	at org.openbase.bco.authentication.lib.com.AbstractAuthenticatedConfigurableController.<init>(AbstractAuthenticatedConfigurableController.java:46)
	at org.openbase.bco.dal.lib.layer.unit.AbstractUnitController.<init>(AbstractUnitController.java:118)
	at org.openbase.bco.dal.lib.layer.unit.AbstractBaseUnitController.<init>(AbstractBaseUnitController.java:37)
	at org.openbase.bco.dal.lib.layer.unit.AbstractHostUnitController.<init>(AbstractHostUnitController.java:67)
	at org.openbase.bco.manager.device.core.AbstractDeviceController.<init>(AbstractDeviceController.java:53)
	at org.openbase.bco.manager.device.core.GenericDeviceController.<init>(GenericDeviceController.java:39)
	at org.openbase.bco.manager.device.core.AbstractDeviceControllerFactory.newInstance(AbstractDeviceControllerFactory.java:76)
	at org.openbase.bco.manager.device.core.DeviceControllerFactoryImpl.newInstance(DeviceControllerFactoryImpl.java:45)
	at org.openbase.bco.manager.device.core.DeviceControllerFactoryImpl.newInstance(DeviceControllerFactoryImpl.java:34)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.register(RegistrySynchronizer.java:102)
	at org.openbase.jul.storage.registry.ActivatableEntryRegistrySynchronizer.register(ActivatableEntryRegistrySynchronizer.java:59)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.register(RegistrySynchronizer.java:93)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.register(RegistrySynchronizer.java:44)
	at org.openbase.jul.storage.registry.AbstractSynchronizer.registerInternal(AbstractSynchronizer.java:244)
	at org.openbase.jul.storage.registry.AbstractSynchronizer.internalSync(AbstractSynchronizer.java:172)
	at org.openbase.jul.storage.registry.AbstractSynchronizer.access$000(AbstractSynchronizer.java:47)
	at org.openbase.jul.storage.registry.AbstractSynchronizer$1.relay(AbstractSynchronizer.java:79)
	at org.openbase.jul.schedule.RecurrenceEventFilter.relay(RecurrenceEventFilter.java:231)
	at org.openbase.jul.schedule.RecurrenceEventFilter.callRelay(RecurrenceEventFilter.java:216)
	at org.openbase.jul.schedule.RecurrenceEventFilter.access$100(RecurrenceEventFilter.java:41)
	at org.openbase.jul.schedule.RecurrenceEventFilter$1.expired(RecurrenceEventFilter.java:90)
	at org.openbase.jul.schedule.Timeout$1.call(Timeout.java:186)
	at org.openbase.jul.schedule.Timeout$1.call(Timeout.java:167)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
09:56:33.181 [pool-2-thread-4] ERROR o.o.j.s.RecurrenceEventFilter =====================================
09:56:33.186 [Thread-600] INFO  o.o.b.d.r.u.ColorableLightRemote Remote connection to Controller[/home/badezimmer/colorablelight/spiegellampe/] was detached because the controller shutdown was initiated.
09:56:33.194 [pool-1-thread-86] WARN  o.o.b.d.r.u.ColorableLightRemote Something went wrong during data request, maybe the connection or activation state has just changed so all checks will be performed again...
org.openbase.jul.exception.InvalidStateException: Could not call Method[requestStatus] asynchronous because of a middleware issue!
	at org.openbase.jul.extension.rsb.com.RSBSynchronizedRemoteServer.callAsync(RSBSynchronizedRemoteServer.java:138)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.internalRequestStatus(RSBRemoteService.java:1140)
	at org.openbase.bco.authentication.lib.com.AbstractAuthenticatedConfigurableRemote.internalRequestStatus(AbstractAuthenticatedConfigurableRemote.java:62)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService$SyncTaskCallable.call(RSBRemoteService.java:1067)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService$SyncTaskCallable.call(RSBRemoteService.java:1010)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: null
	at rsb.transport.spread.SpreadReceiver$State.activate(SpreadReceiver.java:197)
	at rsb.transport.spread.SpreadReceiver.activate(SpreadReceiver.java:344)
	at rsb.transport.spread.SpreadMultiReceiver.subscribe(SpreadMultiReceiver.java:246)
	at rsb.transport.spread.MultiSpreadInPushConnector.activate(MultiSpreadInPushConnector.java:114)
	at rsb.eventprocessing.RouteConfiguratorUtility.activate(RouteConfiguratorUtility.java:90)
	at rsb.eventprocessing.DefaultPushInRouteConfigurator.activate(DefaultPushInRouteConfigurator.java:69)
	at rsb.Listener$StateInactive.activate(Listener.java:122)
	at rsb.Listener.activate(Listener.java:190)
	at rsb.patterns.Method$StateInactive.activate(Method.java:108)
	at rsb.patterns.Method.activate(Method.java:201)
	at rsb.patterns.RemoteServer.addMethod(RemoteServer.java:452)
	at rsb.patterns.RemoteServer.callAsyncEvent(RemoteServer.java:394)
	at rsb.patterns.RemoteServer.callAsync(RemoteServer.java:116)
	at rsb.patterns.RemoteServer.callAsync(RemoteServer.java:137)
	at org.openbase.jul.extension.rsb.com.RSBSynchronizedRemoteServer.callAsync(RSBSynchronizedRemoteServer.java:130)
	... 8 common frames omitted
09:56:33.214 [pool-1-thread-93] WARN  o.o.j.e.r.c.RSBSynchronizedParticipant ═╦═⚀ RSB Participant[rsb.patterns.RemoteServer@71d2c086] deactivation bug detected!
09:56:33.214 [pool-1-thread-93] WARN  o.o.j.e.r.c.RSBSynchronizedParticipant  ╚════⚀ deactivate() cannot be called in state StateInactive
09:56:33.214 [pool-1-thread-93] WARN  o.o.j.e.r.c.RSBSynchronizedParticipant =====================================
09:56:33.221 [pool-1-thread-83] WARN  o.o.j.e.r.c.RSBSynchronizedParticipant ═╦═⚀ RSB Participant[rsb.patterns.RemoteServer@62e2dae5] deactivation bug detected!
09:56:33.222 [pool-1-thread-83] WARN  o.o.j.e.r.c.RSBSynchronizedParticipant  ╚════⚀ deactivate() cannot be called in state StateInactive
09:56:33.222 [pool-1-thread-83] WARN  o.o.j.e.r.c.RSBSynchronizedParticipant =====================================
09:56:33.221 [pool-1-thread-99] WARN  o.o.j.e.r.c.RSBSynchronizedParticipant ═╦═⚀ RSB Participant[rsb.patterns.RemoteServer@ced7686] deactivation bug detected!
09:56:33.222 [pool-1-thread-99] WARN  o.o.j.e.r.c.RSBSynchronizedParticipant  ╚════⚀ deactivate() cannot be called in state StateInactive
09:56:33.222 [pool-1-thread-99] WARN  o.o.j.e.r.c.RSBSynchronizedParticipant =====================================
</pre>

**Comment by pLeminoq** [comment]
This is probably fixed with fixing #114 and #115. If it occurs again reopen.
