### ISSUE TITLE
Fatal implementation error while adding meta config entries.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#134]
The following Exception occurs if new meta config entries are added via the registry editor.

I could not figure out how to reproduce the error but it seems not to limit the editing functionality.
Current workaround: It seems that the apply button has just to be pressed twice.

<pre>
12:51:52.134 [JavaFX Application Thread] ERROR j.lang.Thread ═╦═⚀ Fatal implementation error in or by using Thread[JavaFX Application Thread,5,main]: UncaughtException found!
12:51:52.134 [JavaFX Application Thread] ERROR j.lang.Thread  ╚════⚀ 1
12:51:52.134 [JavaFX Application Thread] ERROR j.lang.Thread =====================================
12:51:52.135 [JavaFX Application Thread] ERROR j.lang.Thread Fatal implementation error in or by using Thread[JavaFX Application Thread,5,main]: UncaughtException found!
org.openbase.jul.exception.FatalImplementationErrorException: Fatal implementation error in or by using Thread[JavaFX Application Thread,5,main]: UncaughtException found!
	at org.openbase.jul.schedule.AbstractExecutorService$1.uncaughtException(AbstractExecutorService.java:92)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:363)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
	at javafx.scene.Node$FocusedProperty.notifyListeners(Node.java:7718)
	at javafx.scene.Node.setFocused(Node.java:7771)
	at javafx.scene.Scene$KeyHandler.setWindowFocused(Scene.java:3932)
	at javafx.scene.Scene$KeyHandler.lambda$new$11(Scene.java:3954)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
	at javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:103)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setFocused(Window.java:452)
	at com.sun.javafx.stage.WindowPeerListener.changedFocused(WindowPeerListener.java:59)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:101)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$422(GlassWindowEventHandler.java:151)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:149)
	at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1270)
	at com.sun.glass.ui.Window.notifyFocus(Window.java:1249)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.openbase.bco.registry.editor.struct.editing.MetaConfigEntryEditingGraphic.updateBuilder(MetaConfigEntryEditingGraphic.java:45)
	at org.openbase.bco.registry.editor.struct.editing.MetaConfigEntryEditingGraphic.updateBuilder(MetaConfigEntryEditingGraphic.java:34)
	at org.openbase.bco.registry.editor.struct.editing.AbstractBuilderEditingGraphic.getCurrentValue(AbstractBuilderEditingGraphic.java:57)
	at org.openbase.bco.registry.editor.struct.editing.AbstractBuilderEditingGraphic.getCurrentValue(AbstractBuilderEditingGraphic.java:33)
	at org.openbase.bco.registry.editor.struct.editing.AbstractEditingGraphic.commitEdit(AbstractEditingGraphic.java:163)
	at org.openbase.bco.registry.editor.struct.editing.AbstractBuilderEditingGraphic.commitEdit(AbstractBuilderEditingGraphic.java:51)
	at org.openbase.bco.registry.editor.struct.editing.AbstractEditingGraphic.lambda$initFocusLossHandling$2(AbstractEditingGraphic.java:142)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	... 25 common frames omitted
</pre>

**Comment by DivineThreepwood** [comment]
Issue moved to [openbase/bco.registry.editor #43](https://github.com/openbase/bco.registry.editor/issues/43) via [**ZenHub**](https://www.zenhub.com/)
