### ISSUE TITLE
Jul Test Failures

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#141]
Sometimes, jul tests are failing because of the following test issue:
<pre>
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.597 sec <<< FAILURE!
testNotification(org.openbase.jul.extension.rsb.com.AbstractControllerServerTest)  Time elapsed: 0.522 sec  <<< FAILURE!
java.lang.AssertionError: Even though wait for data returned the pinging immediatly afterwards failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.openbase.jul.extension.rsb.com.AbstractControllerServerTest.testNotification(AbstractControllerServerTest.java:379)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</pre>

**Comment by DivineThreepwood** [comment]
This issue still occurs sometimes. Please investigate.

**Comment by DivineThreepwood** [comment]
Has been fixed by reimplementation of controller preparation see openbase/jul@dfc7d035
