### ISSUE TITLE
NullPointerException when adding ServiceStateObserver

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.dal#158]
There are currently two issues that can lead to a null pointer exception if a service state observer is added to a unit:
* [x] The unit does not support the given service type. I would suggest to throw a NotAvailableException in these cases.
* [x] The service type UNKNOWN leads to the same error even though I expected that the observer is registered for every available service type.

**Comment by DivineThreepwood** [comment]
Is this always reproducible? Otherwise, can you offer any stack traces?

**Comment by pLeminoq** [comment]
This is always reproducible. Here is a stack trace:
<pre>
java.lang.NullPointerException: null                                                                                                                                                                                 
        at org.openbase.bco.dal.remote.layer.unit.AbstractUnitRemote.addServiceStateObserver(AbstractUnitRemote.java:274)                                                                                            
        at org.openbase.bco.app.openapiserver.spring.UnitApiController.getUnitEvents(UnitApiController.java:148)                                                                                                     
        at org.openbase.bco.app.openapiserver.spring.UnitApiController$$FastClassBySpringCGLIB$$51721e62.invoke(<generated>)
</pre>

**Comment by DivineThreepwood** [comment]
Thanks for the report, both issue has been addressed. There is an InvalidStateException thrown In case the service state is not supported. If the service type is declared as UNKNOWN, then all available service states are observed. Please close issue if everything is working like you expected.
