### ISSUE TITLE
Fatal error after cancellation of a future

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.dal#43]
During a test the BrightnessLightSavingAgent cancelled a future which changed the powerState on a location. The following exception occured: 
<pre>
10:52:41.272 [Thread-1623] ERROR o.o.b.d.r.u.l.LocationRemote ═╦═⚀ Could not notify data update to all observer!
10:52:41.272 [Thread-1623] ERROR o.o.b.d.r.u.l.LocationRemote  ╚══╦═⚄ Could not notify Data[id: "5bdf7a83-9a14-48f0-a134-9b247c082e49"label: "Paradise"color_state {  color {    type: HSB    hsb_color {      hue: 0.0      saturation: 0.0      brightness: 0.0    }  }  timestamp {    time: 0  }}illuminance_state {  illuminance: 2000.0  illuminance_data_unit: LUX  timestamp {    time: 0  }}presence_state {  value: ABSENT  last_presence {    time: 1494579159352000  }}power_state {  value: OFF  timestamp {    time: 1494579161256000  }}blind_state {  movement_state: STOP  opening_ratio: 0.0  timestamp {    time: 0  }}target_temperature_state {  temperature: 0.0  timestamp {    time: 0  }}motion_state {  value: NO_MOTION  last_motion {    time: 0  }  timestamp {    time: 0  }}smoke_alarm_state {  value: NO_ALARM  timestamp {    time: 0  }}smoke_state {  value: NO_SMOKE  smoke_level: 0.0  timestamp {    time: 0  }}temperature_state {  temperature: 0.0  timestamp {    time: 0  }}power_consumption_state {  consumption: 0.0  current: 0.0  voltage: 0.0  timestamp {    time: 0  }}tamper_state {  value: NO_TAMPER  last_detection {    time: 0  }  timestamp {    time: 0  }}] to all observer!
10:52:41.272 [Thread-1623] ERROR o.o.b.d.r.u.l.LocationRemote     ╚════⚀ CancellationException
10:52:41.272 [Thread-1623] ERROR o.o.b.d.r.u.l.LocationRemote =====================================
10:52:41.299 [Thread-1623] ERROR o.o.b.d.r.u.l.LocationRemote Could not notify data update to all observer!
org.openbase.jul.exception.CouldNotPerformException: Could not notify data update to all observer!
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.applyDataUpdate(RSBRemoteService.java:1145)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.access$900(RSBRemoteService.java:72)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService$InternalUpdateHandler.internalNotify(RSBRemoteService.java:1079)
	at rsb.eventprocessing.SingleThreadEventReceivingStrategy$DispatchThread.run(SingleThreadEventReceivingStrategy.java:98)
Caused by: org.openbase.jul.exception.MultiException: Could not notify Data[id: "5bdf7a83-9a14-48f0-a134-9b247c082e49"
...
] to all observer!
	at org.openbase.jul.exception.MultiException.checkAndThrow(MultiException.java:62)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:254)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:165)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.applyDataUpdate(RSBRemoteService.java:1143)
	... 3 common frames omitted
Caused by: java.util.concurrent.CancellationException: null
	at java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openbase.bco.manager.agent.core.preset.BrightnessLightSavingAgent.deallocateResourceIteratively(BrightnessLightSavingAgent.java:140)
	at org.openbase.bco.manager.agent.core.preset.BrightnessLightSavingAgent.lambda$new$0(BrightnessLightSavingAgent.java:72)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:215)
	... 5 common frames omitted
</pre>
Afterwards all remotes lost their connection to the controller instances.

**Comment by DivineThreepwood** [comment]
hopefully fixed by openbase/jul#fd13047

**Comment by DivineThreepwood** [comment]
issue was fixed during RSBRemoteService reimplementation of the data sync last week.
