### ISSUE TITLE
Fix Memory Leak

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#73]
There seems to be a memory leak caused by submitting actions:
<pre>
09:43:27.746 [Thread-330] INFO  o.o.b.m.d.b.o.e.OpenHABCommandExecutor receiveUpdate [Power_Plug_1__chillerstrasse_eingang__PowerConsumptionSensor__Lichterkette__PowerConsumptionStateService=DECIMAL]
09:43:36.550 [Thread-330] INFO  o.o.b.m.d.b.o.e.OpenHABCommandExecutor receiveUpdate [Philips_Hue_E27_Gen1__chillerstrasse_schlafzimmer__ColorableLight__DeckenLampe__PowerStateService=ONOFF]
Exception in thread "Thread-330" java.lang.OutOfMemoryError: Java heap space
09:57:31.180 [pool-2-thread-2] INFO  o.o.b.m.a.c.p.StandbyAgent Standby Bad...
09:57:31.221 [pool-2-thread-2] INFO  o.o.b.m.a.c.p.StandbyAgent Switch off all devices in the Bad
09:57:31.227 [Thread-2889] INFO  o.o.b.d.l.l.u.ColorableLightController $AUTHORITY changed POWER_STATE_SERVICE of unit $LABEL to value: OFF
</pre>

Profile and fix this leak.

**Comment by DivineThreepwood** [comment]
After running the benchmark mode vor 4 days the memory limit scales to 1.5 gb in a stable way.
There seems to be no memory leak.

**Comment by DivineThreepwood** [comment]
Memory leak occurred again!
16:45:00.980 [Thread-1462] ERROR o.o.b.d.l.l.u.ColorableLightController ═╦═⚀ org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!
16:45:00.980 [Thread-1462] ERROR o.o.b.d.l.l.u.ColorableLightController  ╚══╦═⚀ Could not invoke Method[Class applyAction(ActionDescription)]!
16:45:00.980 [Thread-1462] ERROR o.o.b.d.l.l.u.ColorableLightController     ╚══╦═⚀ java.lang.OutOfMemoryError: Java heap space
16:45:00.980 [Thread-1462] ERROR o.o.b.d.l.l.u.ColorableLightController        ╚════⚀ Java heap space
16:45:00.980 [Thread-1462] ERROR o.o.b.d.l.l.u.ColorableLightController =====================================
16:45:00.980 [Thread-1462] ERROR o.o.b.d.l.l.u.ColorableLightController org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!
rsb.patterns.Callback$UserCodeException: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!
        at org.openbase.jul.extension.rsb.com.RPCHelper$1.internalInvoke(RPCHelper.java:99)
        at rsb.patterns.LocalMethod.internalNotify(LocalMethod.java:101)
        at rsb.eventprocessing.SingleThreadEventReceivingStrategy$DispatchThread.run(SingleThreadEventReceivingStrategy.java:100)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!
        ... 3 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.openbase.jul.extension.rsb.com.RPCHelper$1.internalInvoke(RPCHelper.java:85)
        ... 2 common frames omitted
Caused by: java.lang.OutOfMemoryError: Java heap space
16:45:00.980 [Thread-1462] ERROR o.o.b.d.l.l.u.ColorableLightController =====================================
Jan 05, 2018 4:45:00 PM rsb.patterns.LocalMethod internalNotify
WARNING: Exception during method invocation in participant: /chillerstrasse/schlafzimmer/colorablelight/deckenlampe/ctrl/applyAction/. Exception message: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!
<pre>

</pre>

**Comment by DivineThreepwood** [comment]
Issue seems to be fixed or at least it did not occur again. 
Because we can not reproduce the issue even with heavy benchmark performance test we move this issue to "review" state. If it does not occur again within the next month be can close this issue.

**Comment by DivineThreepwood** [comment]
did not occur again.
