### ISSUE TITLE
NullpointerException when deactivating a Scene

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.dal#74]
When deactivating a scene the following Nullpointer is possible:
<pre>
13:09:32.876 [Thread-1102] ERROR o.o.b.m.s.c.SceneControllerImpl ═╦═⚀ org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!
13:09:32.877 [Thread-1102] ERROR o.o.b.m.s.c.SceneControllerImpl  ╚══╦═⚀ Could not invoke Method[Class applyAction(ActionDescription)]!
13:09:32.877 [Thread-1102] ERROR o.o.b.m.s.c.SceneControllerImpl     ╚══╦═⚀ java.util.concurrent.ExecutionException: org.openbase.jul.exception.CouldNotPerformException: Could not Deactive SceneControllerImpl[SCENE[AllesAus]]
13:09:32.877 [Thread-1102] ERROR o.o.b.m.s.c.SceneControllerImpl        ╚══╦═⚀ org.openbase.jul.exception.CouldNotPerformException: Could not Deactive SceneControllerImpl[SCENE[AllesAus]]
13:09:32.877 [Thread-1102] ERROR o.o.b.m.s.c.SceneControllerImpl           ╚══╦═⚀ Could not Deactive SceneControllerImpl[SCENE[AllesAus]]
13:09:32.877 [Thread-1102] ERROR o.o.b.m.s.c.SceneControllerImpl              ╚════⚀ NullPointerException
13:09:32.877 [Thread-1102] ERROR o.o.b.m.s.c.SceneControllerImpl =====================================
13:09:32.911 [Thread-844] ERROR o.o.b.m.s.c.SceneControllerImpl ═╦═⚀ org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!
13:09:32.912 [Thread-844] ERROR o.o.b.m.s.c.SceneControllerImpl  ╚══╦═⚀ Could not invoke Method[Class applyAction(ActionDescription)]!
13:09:32.912 [Thread-844] ERROR o.o.b.m.s.c.SceneControllerImpl     ╚══╦═⚀ java.util.concurrent.ExecutionException: org.openbase.jul.exception.CouldNotPerformException: Could not Deactive SceneControllerImpl[SCENE[Aufräumen]]
13:09:32.912 [Thread-844] ERROR o.o.b.m.s.c.SceneControllerImpl        ╚══╦═⚀ org.openbase.jul.exception.CouldNotPerformException: Could not Deactive SceneControllerImpl[SCENE[Aufräumen]]
13:09:32.912 [Thread-844] ERROR o.o.b.m.s.c.SceneControllerImpl           ╚══╦═⚀ Could not Deactive SceneControllerImpl[SCENE[Aufräumen]]
13:09:32.912 [Thread-844] ERROR o.o.b.m.s.c.SceneControllerImpl              ╚════⚀ NullPointerException
13:09:32.912 [Thread-844] ERROR o.o.b.m.s.c.SceneControllerImpl =====================================
13:09:32.926 [Thread-844] ERROR o.o.b.m.s.c.SceneControllerImpl org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!
rsb.patterns.Callback$UserCodeException: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!
	at org.openbase.jul.extension.rsb.com.RPCHelper$1.internalInvoke(RPCHelper.java:98)
	at rsb.patterns.LocalMethod.internalNotify(LocalMethod.java:101)
	at rsb.eventprocessing.SingleThreadEventReceivingStrategy$DispatchThread.run(SingleThreadEventReceivingStrategy.java:100)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!
	... 3 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.openbase.jul.exception.CouldNotPerformException: Could not Deactive SceneControllerImpl[SCENE[Aufräumen]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openbase.jul.extension.rsb.com.RPCHelper$1.internalInvoke(RPCHelper.java:84)
	... 2 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.openbase.jul.exception.CouldNotPerformException: Could not Deactive SceneControllerImpl[SCENE[Aufräumen]]
	at org.openbase.bco.dal.lib.action.ActionImpl.lambda$internalExecuteWithoutResourceAllocation$2(ActionImpl.java:260)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not Deactive SceneControllerImpl[SCENE[Aufräumen]]
	at org.openbase.bco.dal.lib.layer.unit.AbstractExecutableBaseUnitController.setActivationState(AbstractExecutableBaseUnitController.java:129)
	at sun.reflect.GeneratedMethodAccessor1618.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openbase.bco.dal.lib.layer.service.Service.invokeServiceMethod(Service.java:243)
	at org.openbase.bco.dal.lib.action.ActionImpl.lambda$internalExecuteWithoutResourceAllocation$2(ActionImpl.java:252)
	... 4 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.openbase.bco.dal.lib.layer.unit.AbstractExecutableBaseUnitController.cancelExecution(AbstractExecutableBaseUnitController.java:197)
	at org.openbase.bco.dal.lib.layer.unit.AbstractExecutableBaseUnitController.setActivationState(AbstractExecutableBaseUnitController.java:106)
	... 9 common frames omitted
</pre>

The Nullpointer is received because isDone is called on a future which is currently null. I think the problem is that the SceneControllerImpl is overwriting the isExecuting method.

**Comment by pLeminoq** [comment]
Should be fixed by commits:

* 9a1592d0643a920554f01818891e1ce86671981b
* openbase/bco.manager@5e6dbb4b454ce957bab212aced8c010c5862d6d6

@DivineThreepwood  Should theses commits also be added to the release 1.4?

**Comment by DivineThreepwood** [comment]
yes and done
