### ISSUE TITLE
Fix ColorStateServiceSimulator in bco simulation mode.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#85]
Currently the bco simulation mode is throwing the following exception again and again:

<pre>
7:58:04.173 [pool-2-thread-6] ERROR o.o.b.d.l.s.s.ColorStateServiceSimulator =====================================
17:58:06.637 [pool-2-thread-3] ERROR o.o.b.d.l.s.s.ColorStateServiceSimulator ═╦═⚀ Could not apply service modification!
17:58:06.637 [pool-2-thread-3] ERROR o.o.b.d.l.s.s.ColorStateServiceSimulator  ╚══╦═⚀ Could not apply service[COLOR_STATE_SERVICE] update[color {  hsb_color {    hue: 293.0    saturation: 64.0    brightness: 66.0  }}timestamp {  time: 1518109086636000}] for ColorableLightController[COLORABLE_LIGHT[LLamp3]]!
17:58:06.637 [pool-2-thread-3] ERROR o.o.b.d.l.s.s.ColorStateServiceSimulator     ╚════⚀ Color state unknown!
17:58:06.637 [pool-2-thread-3] ERROR o.o.b.d.l.s.s.ColorStateServiceSimulator =====================================
17:58:06.637 [pool-2-thread-3] ERROR o.o.b.d.l.s.s.ColorStateServiceSimulator Could not apply service modification!
org.openbase.jul.exception.CouldNotPerformException: Could not apply service modification!
	at org.openbase.jul.exception.printer.ExceptionPrinter.printHistory(ExceptionPrinter.java:174)
	at org.openbase.bco.dal.lib.simulation.service.AbstractScheduledServiceSimulator.lambda$new$0(AbstractScheduledServiceSimulator.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not apply service[COLOR_STATE_SERVICE] update[color {
  hsb_color {
    hue: 293.0
    saturation: 64.0
    brightness: 66.0
  }
}
timestamp {
  time: 1518109086636000
}
] for ColorableLightController[COLORABLE_LIGHT[LLamp3]]!
	at org.openbase.bco.dal.lib.layer.unit.AbstractUnitController.applyDataUpdate(AbstractUnitController.java:645)
	at org.openbase.bco.dal.lib.simulation.service.AbstractScheduledServiceSimulator.lambda$new$0(AbstractScheduledServiceSimulator.java:97)
	... 7 common frames omitted
Caused by: org.openbase.jul.exception.VerificationFailedException: Color state unknown!
	at org.openbase.bco.dal.lib.layer.service.provider.ColorStateProviderService.verifyColorState(ColorStateProviderService.java:75)
	at sun.reflect.GeneratedMethodAccessor1840.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openbase.bco.dal.lib.layer.service.Services.verifyServiceState(Services.java:372)
	at org.openbase.bco.dal.lib.layer.unit.AbstractUnitController.applyDataUpdate(AbstractUnitController.java:631)
	... 8 common frames omitted
17:58:06.637 [pool-2-thread-3] ERROR o.o.b.d.l.s.s.ColorStateServiceSimulator =====================================
</pre>

**Comment by pLeminoq** [comment]
Issue occurred for an old version so it was already fixed.
