### ISSUE TITLE
Fix BlindStateServiceSimulator in bco simulation mode.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#86]
The following exception occurs during simulation mode.

<pre>
18:01:29.263 [pool-2-thread-2] ERROR o.o.b.d.l.s.s.BlindStateServiceSimulator ═╦═⚀ Could not apply service modification!
18:01:29.263 [pool-2-thread-2] ERROR o.o.b.d.l.s.s.BlindStateServiceSimulator  ╚══╦═⚀ Could not apply service[BLIND_STATE_SERVICE] update[movement_state: UPopening_ratio: 40.0timestamp {  time: 1518109289263000}] for RollerShutterController[ROLLER_SHUTTER[MiddleInside]]!
18:01:29.263 [pool-2-thread-2] ERROR o.o.b.d.l.s.s.BlindStateServiceSimulator     ╚══╦═⚀ BlindState not valid!
18:01:29.263 [pool-2-thread-2] ERROR o.o.b.d.l.s.s.BlindStateServiceSimulator        ╚══╦═⚀ MovementState and OpeningRatio not available!
18:01:29.263 [pool-2-thread-2] ERROR o.o.b.d.l.s.s.BlindStateServiceSimulator           ╚════⚀ timestamp {  time: 1518109289263000}
18:01:29.263 [pool-2-thread-2] ERROR o.o.b.d.l.s.s.BlindStateServiceSimulator =====================================
18:01:29.263 [pool-2-thread-2] ERROR o.o.b.d.l.s.s.BlindStateServiceSimulator Could not apply service modification!
org.openbase.jul.exception.CouldNotPerformException: Could not apply service modification!
	at org.openbase.jul.exception.printer.ExceptionPrinter.printHistory(ExceptionPrinter.java:174)
	at org.openbase.bco.dal.lib.simulation.service.AbstractScheduledServiceSimulator.lambda$new$0(AbstractScheduledServiceSimulator.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not apply service[BLIND_STATE_SERVICE] update[movement_state: UP
opening_ratio: 40.0
timestamp {
  time: 1518109289263000
}
] for RollerShutterController[ROLLER_SHUTTER[MiddleInside]]!
	at org.openbase.bco.dal.lib.layer.unit.AbstractUnitController.applyDataUpdate(AbstractUnitController.java:645)
	at org.openbase.bco.dal.lib.simulation.service.AbstractScheduledServiceSimulator.lambda$new$0(AbstractScheduledServiceSimulator.java:97)
	... 7 common frames omitted
Caused by: org.openbase.jul.exception.VerificationFailedException: BlindState not valid!
	at org.openbase.bco.dal.lib.layer.service.provider.BlindStateProviderService.verifyBlindState(BlindStateProviderService.java:59)
	at sun.reflect.GeneratedMethodAccessor1940.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openbase.bco.dal.lib.layer.service.Services.verifyServiceState(Services.java:372)
	at org.openbase.bco.dal.lib.layer.unit.AbstractUnitController.applyDataUpdate(AbstractUnitController.java:631)
	... 8 common frames omitted
Caused by: org.openbase.jul.exception.VerificationFailedException: MovementState and OpeningRatio not available!
	at org.openbase.bco.dal.lib.layer.service.provider.BlindStateProviderService.verifyBlindState(BlindStateProviderService.java:43)
	... 13 common frames omitted
Caused by: org.openbase.jul.exception.InvalidStateException: timestamp {
  time: 1518109289263000
}

	... 14 common frames omitted
18:01:29.263 [pool-2-thread-2] ERROR o.o.b.d.l.s.s.BlindStateServiceSimulator =====================================
</pre>

Please find and fix the bug.

**Comment by pLeminoq** [comment]
Issue occurred for an old version so it was already fixed.
